// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pustok.Data;

#nullable disable

namespace Pustok.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251214083533_mig_4")]
    partial class mig_4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pustok.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "F. Scott Fitzgerald"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Harper Lee"
                        },
                        new
                        {
                            Id = 3,
                            Name = "George Orwell"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Jane Austen"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mark Twain"
                        });
                });

            modelBuilder.Entity("Pustok.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<string>("HoverImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<string>("MainImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Code = "BK001",
                            Description = "A classic novel set in the Jazz Age",
                            DiscountPercent = 10,
                            HoverImageUrl = "great-gatsby-hover.jpg",
                            InStock = true,
                            IsFeatured = true,
                            IsNew = false,
                            MainImageUrl = "great-gatsby.jpg",
                            Name = "The Great Gatsby",
                            Price = 15.99m
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            Code = "BK002",
                            Description = "A gripping tale of racial injustice",
                            DiscountPercent = 15,
                            HoverImageUrl = "mockingbird-hover.jpg",
                            InStock = true,
                            IsFeatured = true,
                            IsNew = false,
                            MainImageUrl = "mockingbird.jpg",
                            Name = "To Kill a Mockingbird",
                            Price = 18.50m
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            Code = "BK003",
                            Description = "A dystopian social science fiction novel",
                            DiscountPercent = 0,
                            HoverImageUrl = "1984-hover.jpg",
                            InStock = true,
                            IsFeatured = false,
                            IsNew = true,
                            MainImageUrl = "1984.jpg",
                            Name = "1984",
                            Price = 14.99m
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            Code = "BK004",
                            Description = "A romantic novel of manners",
                            DiscountPercent = 20,
                            HoverImageUrl = "pride-prejudice-hover.jpg",
                            InStock = true,
                            IsFeatured = true,
                            IsNew = false,
                            MainImageUrl = "pride-prejudice.jpg",
                            Name = "Pride and Prejudice",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 5,
                            Code = "BK005",
                            Description = "A classic American adventure novel",
                            DiscountPercent = 5,
                            HoverImageUrl = "huckleberry-finn-hover.jpg",
                            InStock = true,
                            IsFeatured = false,
                            IsNew = true,
                            MainImageUrl = "huckleberry-finn.jpg",
                            Name = "Adventures of Huckleberry Finn",
                            Price = 13.50m
                        });
                });

            modelBuilder.Entity("Pustok.Models.BookImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("BookImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            ImageUrl = "great-gatsby-detail1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            BookId = 1,
                            ImageUrl = "great-gatsby-detail2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            BookId = 2,
                            ImageUrl = "mockingbird-detail1.jpg"
                        },
                        new
                        {
                            Id = 4,
                            BookId = 2,
                            ImageUrl = "mockingbird-detail2.jpg"
                        },
                        new
                        {
                            Id = 5,
                            BookId = 3,
                            ImageUrl = "1984-detail1.jpg"
                        },
                        new
                        {
                            Id = 6,
                            BookId = 3,
                            ImageUrl = "1984-detail2.jpg"
                        },
                        new
                        {
                            Id = 7,
                            BookId = 4,
                            ImageUrl = "pride-prejudice-detail1.jpg"
                        },
                        new
                        {
                            Id = 8,
                            BookId = 4,
                            ImageUrl = "pride-prejudice-detail2.jpg"
                        },
                        new
                        {
                            Id = 9,
                            BookId = 5,
                            ImageUrl = "huckleberry-finn-detail1.jpg"
                        },
                        new
                        {
                            Id = 10,
                            BookId = 5,
                            ImageUrl = "huckleberry-finn-detail2.jpg"
                        });
                });

            modelBuilder.Entity("Pustok.Models.BookTag", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("BookTags");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            TagId = 1
                        },
                        new
                        {
                            BookId = 1,
                            TagId = 2
                        },
                        new
                        {
                            BookId = 1,
                            TagId = 3
                        },
                        new
                        {
                            BookId = 2,
                            TagId = 1
                        },
                        new
                        {
                            BookId = 2,
                            TagId = 2
                        },
                        new
                        {
                            BookId = 2,
                            TagId = 8
                        },
                        new
                        {
                            BookId = 3,
                            TagId = 6
                        },
                        new
                        {
                            BookId = 3,
                            TagId = 2
                        },
                        new
                        {
                            BookId = 3,
                            TagId = 3
                        },
                        new
                        {
                            BookId = 4,
                            TagId = 4
                        },
                        new
                        {
                            BookId = 4,
                            TagId = 2
                        },
                        new
                        {
                            BookId = 4,
                            TagId = 3
                        },
                        new
                        {
                            BookId = 5,
                            TagId = 5
                        },
                        new
                        {
                            BookId = 5,
                            TagId = 1
                        },
                        new
                        {
                            BookId = 5,
                            TagId = 2
                        });
                });

            modelBuilder.Entity("Pustok.Models.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Key = "SiteName",
                            Value = "Pustok Bookstore"
                        },
                        new
                        {
                            Key = "SiteEmail",
                            Value = "info@pustok.com"
                        },
                        new
                        {
                            Key = "SitePhone",
                            Value = "+1 (555) 123-4567"
                        },
                        new
                        {
                            Key = "SiteAddress",
                            Value = "123 Book Street, Reading City, RC 12345"
                        },
                        new
                        {
                            Key = "FacebookUrl",
                            Value = "https://facebook.com/pustok"
                        },
                        new
                        {
                            Key = "TwitterUrl",
                            Value = "https://twitter.com/pustok"
                        },
                        new
                        {
                            Key = "InstagramUrl",
                            Value = "https://instagram.com/pustok"
                        },
                        new
                        {
                            Key = "WorkingHours",
                            Value = "Mon - Sat: 9:00 - 18:00"
                        });
                });

            modelBuilder.Entity("Pustok.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ButtonText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ButtonUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ButtonText = "Shop Now",
                            ButtonUrl = "/books",
                            Description = "Your favorite online bookstore",
                            ImageUrl = "slider1.jpg",
                            Order = 1,
                            Title = "Welcome to Pustok"
                        },
                        new
                        {
                            Id = 2,
                            ButtonText = "Explore",
                            ButtonUrl = "/books",
                            Description = "Discover amazing books",
                            ImageUrl = "slider2.jpg",
                            Order = 2,
                            Title = "Best Sellers"
                        },
                        new
                        {
                            Id = 3,
                            ButtonText = "View More",
                            ButtonUrl = "/books",
                            Description = "Check out our latest collection",
                            ImageUrl = "slider3.jpg",
                            Order = 3,
                            Title = "New Arrivals"
                        });
                });

            modelBuilder.Entity("Pustok.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Classic"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bestseller"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Historical"
                        });
                });

            modelBuilder.Entity("Pustok.Models.Book", b =>
                {
                    b.HasOne("Pustok.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Pustok.Models.BookImage", b =>
                {
                    b.HasOne("Pustok.Models.Book", "Book")
                        .WithMany("BookImages")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Pustok.Models.BookTag", b =>
                {
                    b.HasOne("Pustok.Models.Book", "Book")
                        .WithMany("BookTags")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pustok.Models.Tag", "Tag")
                        .WithMany("BookTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Pustok.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Pustok.Models.Book", b =>
                {
                    b.Navigation("BookImages");

                    b.Navigation("BookTags");
                });

            modelBuilder.Entity("Pustok.Models.Tag", b =>
                {
                    b.Navigation("BookTags");
                });
#pragma warning restore 612, 618
        }
    }
}
