// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pustok.Data;

#nullable disable

namespace Pustok.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251214091555_mig_5")]
    partial class mig_5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pustok.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "F. Scott Fitzgerald"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Harper Lee"
                        },
                        new
                        {
                            Id = 3,
                            Name = "George Orwell"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Jane Austen"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mark Twain"
                        },
                        new
                        {
                            Id = 6,
                            Name = "J.K. Rowling"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Ernest Hemingway"
                        });
                });

            modelBuilder.Entity("Pustok.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<string>("HoverImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<string>("MainImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Code = "BK001",
                            Description = "A classic novel set in the Jazz Age",
                            DiscountPercent = 10,
                            HoverImageUrl = "great-gatsby-hover.jpg",
                            InStock = true,
                            IsFeatured = true,
                            IsNew = false,
                            MainImageUrl = "great-gatsby.jpg",
                            Name = "The Great Gatsby",
                            Price = 15.99m
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Code = "BK002",
                            Description = "A story of a psychiatrist's descent into alcoholism",
                            DiscountPercent = 5,
                            HoverImageUrl = "tender-night-hover.jpg",
                            InStock = true,
                            IsFeatured = false,
                            IsNew = false,
                            MainImageUrl = "tender-night.jpg",
                            Name = "Tender Is the Night",
                            Price = 16.99m
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            Code = "BK003",
                            Description = "The debut novel about post-World War I youth",
                            DiscountPercent = 0,
                            HoverImageUrl = "paradise-hover.jpg",
                            InStock = true,
                            IsFeatured = false,
                            IsNew = false,
                            MainImageUrl = "paradise.jpg",
                            Name = "This Side of Paradise",
                            Price = 14.99m
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            Code = "BK004",
                            Description = "A gripping tale of racial injustice",
                            DiscountPercent = 15,
                            HoverImageUrl = "mockingbird-hover.jpg",
                            InStock = true,
                            IsFeatured = true,
                            IsNew = false,
                            MainImageUrl = "mockingbird.jpg",
                            Name = "To Kill a Mockingbird",
                            Price = 18.50m
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 2,
                            Code = "BK005",
                            Description = "A sequel to To Kill a Mockingbird",
                            DiscountPercent = 10,
                            HoverImageUrl = "watchman-hover.jpg",
                            InStock = true,
                            IsFeatured = false,
                            IsNew = true,
                            MainImageUrl = "watchman.jpg",
                            Name = "Go Set a Watchman",
                            Price = 17.99m
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 3,
                            Code = "BK006",
                            Description = "A dystopian social science fiction novel",
                            DiscountPercent = 0,
                            HoverImageUrl = "1984-hover.jpg",
                            InStock = true,
                            IsFeatured = true,
                            IsNew = true,
                            MainImageUrl = "1984.jpg",
                            Name = "1984",
                            Price = 14.99m
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 3,
                            Code = "BK007",
                            Description = "An allegorical novella about Soviet totalitarianism",
                            DiscountPercent = 5,
                            HoverImageUrl = "animal-farm-hover.jpg",
                            InStock = true,
                            IsFeatured = true,
                            IsNew = false,
                            MainImageUrl = "animal-farm.jpg",
                            Name = "Animal Farm",
                            Price = 13.99m
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 3,
                            Code = "BK008",
                            Description = "Orwell's account of the Spanish Civil War",
                            DiscountPercent = 0,
                            HoverImageUrl = "catalonia-hover.jpg",
                            InStock = true,
                            IsFeatured = false,
                            IsNew = false,
                            MainImageUrl = "catalonia.jpg",
                            Name = "Homage to Catalonia",
                            Price = 15.50m
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 4,
                            Code = "BK009",
                            Description = "A romantic novel of manners",
                            DiscountPercent = 20,
                            HoverImageUrl = "pride-prejudice-hover.jpg",
                            InStock = true,
                            IsFeatured = true,
                            IsNew = false,
                            MainImageUrl = "pride-prejudice.jpg",
                            Name = "Pride and Prejudice",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 4,
                            Code = "BK010",
                            Description = "A story of two sisters and their romantic adventures",
                            DiscountPercent = 15,
                            HoverImageUrl = "sense-sensibility-hover.jpg",
                            InStock = true,
                            IsFeatured = false,
                            IsNew = false,
                            MainImageUrl = "sense-sensibility.jpg",
                            Name = "Sense and Sensibility",
                            Price = 13.99m
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 4,
                            Code = "BK011",
                            Description = "A comedy of manners about youthful hubris",
                            DiscountPercent = 10,
                            HoverImageUrl = "emma-hover.jpg",
                            InStock = true,
                            IsFeatured = false,
                            IsNew = false,
                            MainImageUrl = "emma.jpg",
                            Name = "Emma",
                            Price = 14.50m
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 5,
                            Code = "BK012",
                            Description = "A classic American adventure novel",
                            DiscountPercent = 5,
                            HoverImageUrl = "huckleberry-finn-hover.jpg",
                            InStock = true,
                            IsFeatured = true,
                            IsNew = true,
                            MainImageUrl = "huckleberry-finn.jpg",
                            Name = "Adventures of Huckleberry Finn",
                            Price = 13.50m
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 5,
                            Code = "BK013",
                            Description = "A boy's adventures in a Mississippi River town",
                            DiscountPercent = 5,
                            HoverImageUrl = "tom-sawyer-hover.jpg",
                            InStock = true,
                            IsFeatured = false,
                            IsNew = false,
                            MainImageUrl = "tom-sawyer.jpg",
                            Name = "The Adventures of Tom Sawyer",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 6,
                            Code = "BK014",
                            Description = "A young wizard's first year at Hogwarts",
                            DiscountPercent = 25,
                            HoverImageUrl = "hp-stone-hover.jpg",
                            InStock = true,
                            IsFeatured = true,
                            IsNew = true,
                            MainImageUrl = "hp-stone.jpg",
                            Name = "Harry Potter and the Philosopher's Stone",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 6,
                            Code = "BK015",
                            Description = "Harry's second year at Hogwarts",
                            DiscountPercent = 20,
                            HoverImageUrl = "hp-chamber-hover.jpg",
                            InStock = true,
                            IsFeatured = true,
                            IsNew = true,
                            MainImageUrl = "hp-chamber.jpg",
                            Name = "Harry Potter and the Chamber of Secrets",
                            Price = 20.99m
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 6,
                            Code = "BK016",
                            Description = "Harry's third year brings new dangers",
                            DiscountPercent = 20,
                            HoverImageUrl = "hp-azkaban-hover.jpg",
                            InStock = true,
                            IsFeatured = false,
                            IsNew = true,
                            MainImageUrl = "hp-azkaban.jpg",
                            Name = "Harry Potter and the Prisoner of Azkaban",
                            Price = 21.99m
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 7,
                            Code = "BK017",
                            Description = "An aging fisherman's epic struggle with a giant marlin",
                            DiscountPercent = 10,
                            HoverImageUrl = "old-man-sea-hover.jpg",
                            InStock = true,
                            IsFeatured = true,
                            IsNew = false,
                            MainImageUrl = "old-man-sea.jpg",
                            Name = "The Old Man and the Sea",
                            Price = 16.50m
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 7,
                            Code = "BK018",
                            Description = "A love story set during World War I",
                            DiscountPercent = 5,
                            HoverImageUrl = "farewell-arms-hover.jpg",
                            InStock = true,
                            IsFeatured = false,
                            IsNew = false,
                            MainImageUrl = "farewell-arms.jpg",
                            Name = "A Farewell to Arms",
                            Price = 17.99m
                        });
                });

            modelBuilder.Entity("Pustok.Models.BookImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("BookImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            ImageUrl = "great-gatsby-detail1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            BookId = 1,
                            ImageUrl = "great-gatsby-detail2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            BookId = 2,
                            ImageUrl = "tender-night-detail1.jpg"
                        },
                        new
                        {
                            Id = 4,
                            BookId = 2,
                            ImageUrl = "tender-night-detail2.jpg"
                        },
                        new
                        {
                            Id = 5,
                            BookId = 3,
                            ImageUrl = "paradise-detail1.jpg"
                        },
                        new
                        {
                            Id = 6,
                            BookId = 3,
                            ImageUrl = "paradise-detail2.jpg"
                        },
                        new
                        {
                            Id = 7,
                            BookId = 4,
                            ImageUrl = "mockingbird-detail1.jpg"
                        },
                        new
                        {
                            Id = 8,
                            BookId = 4,
                            ImageUrl = "mockingbird-detail2.jpg"
                        },
                        new
                        {
                            Id = 9,
                            BookId = 5,
                            ImageUrl = "watchman-detail1.jpg"
                        },
                        new
                        {
                            Id = 10,
                            BookId = 5,
                            ImageUrl = "watchman-detail2.jpg"
                        },
                        new
                        {
                            Id = 11,
                            BookId = 6,
                            ImageUrl = "1984-detail1.jpg"
                        },
                        new
                        {
                            Id = 12,
                            BookId = 6,
                            ImageUrl = "1984-detail2.jpg"
                        },
                        new
                        {
                            Id = 13,
                            BookId = 7,
                            ImageUrl = "animal-farm-detail1.jpg"
                        },
                        new
                        {
                            Id = 14,
                            BookId = 7,
                            ImageUrl = "animal-farm-detail2.jpg"
                        },
                        new
                        {
                            Id = 15,
                            BookId = 8,
                            ImageUrl = "catalonia-detail1.jpg"
                        },
                        new
                        {
                            Id = 16,
                            BookId = 8,
                            ImageUrl = "catalonia-detail2.jpg"
                        },
                        new
                        {
                            Id = 17,
                            BookId = 9,
                            ImageUrl = "pride-prejudice-detail1.jpg"
                        },
                        new
                        {
                            Id = 18,
                            BookId = 9,
                            ImageUrl = "pride-prejudice-detail2.jpg"
                        },
                        new
                        {
                            Id = 19,
                            BookId = 10,
                            ImageUrl = "sense-sensibility-detail1.jpg"
                        },
                        new
                        {
                            Id = 20,
                            BookId = 10,
                            ImageUrl = "sense-sensibility-detail2.jpg"
                        },
                        new
                        {
                            Id = 21,
                            BookId = 11,
                            ImageUrl = "emma-detail1.jpg"
                        },
                        new
                        {
                            Id = 22,
                            BookId = 11,
                            ImageUrl = "emma-detail2.jpg"
                        },
                        new
                        {
                            Id = 23,
                            BookId = 12,
                            ImageUrl = "huckleberry-finn-detail1.jpg"
                        },
                        new
                        {
                            Id = 24,
                            BookId = 12,
                            ImageUrl = "huckleberry-finn-detail2.jpg"
                        },
                        new
                        {
                            Id = 25,
                            BookId = 13,
                            ImageUrl = "tom-sawyer-detail1.jpg"
                        },
                        new
                        {
                            Id = 26,
                            BookId = 13,
                            ImageUrl = "tom-sawyer-detail2.jpg"
                        },
                        new
                        {
                            Id = 27,
                            BookId = 14,
                            ImageUrl = "hp-stone-detail1.jpg"
                        },
                        new
                        {
                            Id = 28,
                            BookId = 14,
                            ImageUrl = "hp-stone-detail2.jpg"
                        },
                        new
                        {
                            Id = 29,
                            BookId = 15,
                            ImageUrl = "hp-chamber-detail1.jpg"
                        },
                        new
                        {
                            Id = 30,
                            BookId = 15,
                            ImageUrl = "hp-chamber-detail2.jpg"
                        },
                        new
                        {
                            Id = 31,
                            BookId = 16,
                            ImageUrl = "hp-azkaban-detail1.jpg"
                        },
                        new
                        {
                            Id = 32,
                            BookId = 16,
                            ImageUrl = "hp-azkaban-detail2.jpg"
                        },
                        new
                        {
                            Id = 33,
                            BookId = 17,
                            ImageUrl = "old-man-sea-detail1.jpg"
                        },
                        new
                        {
                            Id = 34,
                            BookId = 17,
                            ImageUrl = "old-man-sea-detail2.jpg"
                        },
                        new
                        {
                            Id = 35,
                            BookId = 18,
                            ImageUrl = "farewell-arms-detail1.jpg"
                        },
                        new
                        {
                            Id = 36,
                            BookId = 18,
                            ImageUrl = "farewell-arms-detail2.jpg"
                        });
                });

            modelBuilder.Entity("Pustok.Models.BookTag", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("BookTags");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            TagId = 1
                        },
                        new
                        {
                            BookId = 1,
                            TagId = 2
                        },
                        new
                        {
                            BookId = 1,
                            TagId = 3
                        },
                        new
                        {
                            BookId = 2,
                            TagId = 1
                        },
                        new
                        {
                            BookId = 2,
                            TagId = 2
                        },
                        new
                        {
                            BookId = 2,
                            TagId = 8
                        },
                        new
                        {
                            BookId = 3,
                            TagId = 6
                        },
                        new
                        {
                            BookId = 3,
                            TagId = 2
                        },
                        new
                        {
                            BookId = 3,
                            TagId = 3
                        },
                        new
                        {
                            BookId = 4,
                            TagId = 4
                        },
                        new
                        {
                            BookId = 4,
                            TagId = 2
                        },
                        new
                        {
                            BookId = 4,
                            TagId = 3
                        },
                        new
                        {
                            BookId = 5,
                            TagId = 5
                        },
                        new
                        {
                            BookId = 5,
                            TagId = 1
                        },
                        new
                        {
                            BookId = 5,
                            TagId = 2
                        });
                });

            modelBuilder.Entity("Pustok.Models.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Key = "SiteName",
                            Value = "Pustok Bookstore"
                        },
                        new
                        {
                            Key = "SiteEmail",
                            Value = "info@pustok.com"
                        },
                        new
                        {
                            Key = "SitePhone",
                            Value = "+1 (555) 123-4567"
                        },
                        new
                        {
                            Key = "SiteAddress",
                            Value = "123 Book Street, Reading City, RC 12345"
                        },
                        new
                        {
                            Key = "FacebookUrl",
                            Value = "https://facebook.com/pustok"
                        },
                        new
                        {
                            Key = "TwitterUrl",
                            Value = "https://twitter.com/pustok"
                        },
                        new
                        {
                            Key = "InstagramUrl",
                            Value = "https://instagram.com/pustok"
                        },
                        new
                        {
                            Key = "WorkingHours",
                            Value = "Mon - Sat: 9:00 - 18:00"
                        },
                        new
                        {
                            Key = "logourl",
                            Value = "logo.png"
                        },
                        new
                        {
                            Key = "phone",
                            Value = "+1 (555) 123-4567"
                        },
                        new
                        {
                            Key = "instagram",
                            Value = "https://instagram.com/pustok"
                        },
                        new
                        {
                            Key = "address",
                            Value = "123 Book Street, Reading City, RC 12345"
                        });
                });

            modelBuilder.Entity("Pustok.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ButtonText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ButtonUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ButtonText = "Shop Now",
                            ButtonUrl = "/books",
                            Description = "Your favorite online bookstore",
                            ImageUrl = "slider1.jpg",
                            Order = 1,
                            Title = "Welcome to Pustok"
                        },
                        new
                        {
                            Id = 2,
                            ButtonText = "Explore",
                            ButtonUrl = "/books",
                            Description = "Discover amazing books",
                            ImageUrl = "slider2.jpg",
                            Order = 2,
                            Title = "Best Sellers"
                        },
                        new
                        {
                            Id = 3,
                            ButtonText = "View More",
                            ButtonUrl = "/books",
                            Description = "Check out our latest collection",
                            ImageUrl = "slider3.jpg",
                            Order = 3,
                            Title = "New Arrivals"
                        });
                });

            modelBuilder.Entity("Pustok.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Classic"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bestseller"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Historical"
                        });
                });

            modelBuilder.Entity("Pustok.Models.Book", b =>
                {
                    b.HasOne("Pustok.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Pustok.Models.BookImage", b =>
                {
                    b.HasOne("Pustok.Models.Book", "Book")
                        .WithMany("BookImages")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Pustok.Models.BookTag", b =>
                {
                    b.HasOne("Pustok.Models.Book", "Book")
                        .WithMany("BookTags")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pustok.Models.Tag", "Tag")
                        .WithMany("BookTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Pustok.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Pustok.Models.Book", b =>
                {
                    b.Navigation("BookImages");

                    b.Navigation("BookTags");
                });

            modelBuilder.Entity("Pustok.Models.Tag", b =>
                {
                    b.Navigation("BookTags");
                });
#pragma warning restore 612, 618
        }
    }
}
